config:
  project_repos:
    o3api:
      repo: 'https://git.scc.kit.edu/synergy.o3as/o3api.git'
      branch: master
  credentials:
    - id: o3as-dockerhub-vk
      username_var: JPL_DOCKERUSER
      password_var: JPL_DOCKERPASS
environment:
#  JPL_DOCKERSERVER: "hub.docker.com"
  JPL_DOCKERPUSH: "o3api"
  JPL_DOCKERFORCEBUILD: "True"
#  LANG: C.UTF-8

sqa_criteria:
  qc_style:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv:
            - pep8
  qc_coverage:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv: 
            - cover
            - cobertura
  qc_security:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv:
            - bandit

timeout: 900
