config:
  credentials: []
  project_repos: {}
environment:
  JPL_DOCKERFORCEBUILD: enabled
sqa_criteria:
  QC.Fun:
    repos:
      this_repo:
        commands:
        - tox -c tox.ini -e func-api
        container: processing
  QC.Sty:
    repos:
      this_repo:
        commands:
        - tox -c tox.ini -e pep8
        container: processing
  QC.Uni:
    repos:
      this_repo:
        commands:
        - tox -c tox.ini -e unittest
        container: processing
timeout: 600
