#########
# for local tests:
# 1. build test container, from the o3api source directory:
# docker-compose -f .sqa/docker-compose.yml --project-directory $PWD up --build -d o3api-testing
#
# 2. then run tests as below (See also difinitions in this file)
# docker-compose -f .sqa/docker-compose.yml --project-directory $PWD \
# exec -T -e JPL_DOCKERUSER -e JPL_DOCKERPASS o3api-testing tox -c /o3api-testing/tox.ini -e pep8
#
# docker-compose -f .sqa/docker-compose.yml --project-directory $PWD \
# exec -T -e JPL_DOCKERUSER -e JPL_DOCKERPASS o3api-testing tox -c /o3api-testing/tox.ini -e unittest
#
# docker-compose -f .sqa/docker-compose.yml --project-directory $PWD \
# exec -T -e JPL_DOCKERUSER -e JPL_DOCKERPASS o3api-testing tox -c /o3api-testing/tox.ini -e func-api
#
# docker-compose -f .sqa/docker-compose.yml --project-directory $PWD \
# exec -T -e JPL_DOCKERUSER -e JPL_DOCKERPASS o3api-testing tox -c /o3api-testing/tox.ini -e cobertura
#
# docker-compose -f .sqa/docker-compose.yml --project-directory $PWD \
# exec -T -e JPL_DOCKERUSER -e JPL_DOCKERPASS o3api-testing tox -c /o3api-testing/tox.ini -e bandit

config:
  node_agent: 'docker_compose'
#  project_repos:
#    o3api:
#      repo: 'https://git.scc.kit.edu/synergy.o3as/o3api.git'
#      branch: master
  credentials:
    - id: o3as-dockerhub-vykozlov
      username_var: JPL_DOCKERUSER
      password_var: JPL_DOCKERPASS

environment:
  JPL_DOCKERPUSH: "o3api"
  JPL_DOCKERFORCEBUILD: "True"
  LANG: C.UTF-8

sqa_criteria:
  qc_style:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv:
            - pep8
  qc_coverage:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv: 
            - unittest
  qc_functional:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv: 
            - func-api
            - cobertura
  qc_security:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv:
            - bandit

timeout: 1200
