config:
  node_agent: 'docker_compose'
#  project_repos:
#    o3api:
#      repo: 'https://git.scc.kit.edu/synergy.o3as/o3api.git'
#      branch: master
  credentials:
    - id: o3as-dockerhub-vykozlov
      username_var: JPL_DOCKERUSER
      password_var: JPL_DOCKERPASS

environment:
  JPL_DOCKERPUSH: "o3api"
  JPL_DOCKERFORCEBUILD: "True"
  LANG: C.UTF-8

sqa_criteria:
  qc_style:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv:
            - pep8
  qc_coverage:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv: 
            - unittest
  qc_functional:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv: 
            - func-api
            - cobertura
  qc_security:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv:
            - bandit

timeout: 900
