services:
  qc.fun_lanky-copper-tortoise:
    command: sleep 6000000
    image: painless/tox
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_scummy-gold-moose:
    command: sleep 6000000
    image: painless/tox
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.uni_cheeky-olive-cockroach:
    command: sleep 6000000
    image: painless/tox
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
