version: "3.7"

services:
  o3api-testing:
    image: "indigodatacloud/ci-images:python3.6"
    container_name: "o3api-testing"
    hostname: "o3api-testing"
    volumes:
     - type: bind
       source: ./o3api
       target: /o3api-testing

  o3api:
     build:
        context: "."
        dockerfile: "./o3api/docker/Dockerfile"
     image: "o3as/o3api:test"