version: "3.7"

services:
  o3api-testing:
    image: "indigodatacloud/ci-images:python3.6"
    container_name: "o3api-testing"
    hostname: "o3api-testing"
    volumes:
     - type: bind
       source: ./
       target: /o3api-testing

  o3api:
     build:
        context: "."
        dockerfile: "./docker/Dockerfile"
        args:
          branch: ${GIT_BRANCH}
          api_date: ${O3API_UPDATE_DATE}
     image: "o3as/o3api:${O3API_DOCKER_TAG}"
